# Generated by Django 3.1 on 2020-08-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200807_2259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
