# Generated by Django 3.1 on 2020-08-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20200809_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
