# Generated by Django 3.1 on 2020-08-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20200809_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='starting_date',
            field=models.DateField(default=''),
        ),
    ]
