# Generated by Django 3.1 on 2020-08-09 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_tasks_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 9, 13, 10, 42, 513566, tzinfo=utc)),
        ),
    ]
