# Generated by Django 3.1 on 2020-08-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_auto_20200809_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='starting_date',
            field=models.DateField(blank=True),
        ),
    ]
