# Generated by Django 3.1 on 2020-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0014_auto_20200809_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='starting_date',
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
