# Generated by Django 3.1 on 2020-08-09 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0016_remove_tasks_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='starting_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
