# Generated by Django 3.1 on 2020-08-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0017_tasks_starting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='starting_date',
        ),
    ]
